name: CI

on: [push, workflow_dispatch]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_HUB }} | docker login -u pfremm --password-stdin
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image" --push \
            --tag pfremm/transmission-rss:arm64 .
