name: CI

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Docker login
        run: |
          docker login -u pfremm -p ${DOCKER_PASSWORD} index.docker.io
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=false" \
            --tag pfremm/transmission-rss .
